apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mysuperawesomeapp-hpa
  labels:
    app: mysuperawesomeapp
    version: 0.0.1
    backstage.io/kubernetes-id: mysuperawesomeapp
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: mysuperawesomeapp
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75